# This is a basic workflow to help you get started with Actions

name: 'tests'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          path: avrWDT

      - name: Checkout avrIO
        uses: actions/checkout@main
        with:
          repository: ricardocosme/avrIO
          path: avrIO
          
      - name: Checkout avrINT
        uses: actions/checkout@main
        with:
          repository: ricardocosme/avrINT
          path: avrINT
          
      - name: Build docker image
        run: docker build -t avr-gcc -f avrWDT/.github/workflows/Dockerfile .

      - name: Tests
        run: docker run -v $(pwd):/build -w/build avr-gcc make -B test -C avrWDT
        
